apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-prajna
  namespace: hypermine-development
spec:
  selector:
    matchLabels:
      app: wallet-prajna
  template:
    metadata:
      labels:
        app: wallet-prajna
    spec:
      containers:
        - name: wallet-prajna
          image: pratapmridha/wallet:__LATEST_RELEASE_TAG__
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-prajna-service
  namespace: hypermine-development
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort

  selector:
    app: wallet-prajna
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
