name: Wallet Build and deploy Pipeline

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]-rc.[0-9]+"

jobs:
  Build-Pipeline:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: Set Latest Tag
        run: echo "LATEST_RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: install gcloud cli tools
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GOOGLE_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true
      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker Auth"
        run: gcloud auth configure-docker ${{secrets.GOOGLE_ARTIFACT_URL}}
      - name: "Docker Build and Push"
        env:
          GOOGLE_PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
          GOOGLE_ARTIFACT_URL: ${{secrets.GOOGLE_ARTIFACT_URL}}
          GOOGLE_ARTIFACT_REPO: ${{secrets.GOOGLE_ARTIFACT_REPO}}
        run: docker build -t $GOOGLE_ARTIFACT_URL/$GOOGLE_PROJECT_ID/$GOOGLE_ARTIFACT_REPO/wallet:${{ env.LATEST_RELEASE_TAG }} .
